import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToolbarComponent from "../components/headerComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header><ToolbarComponent /></header>
      <main className={inter.className}>{children}</main>
    </>
  );
}
