import type { Metadata } from "next";
import backgroundImage from "@/public/coffeeShopBackground.jpg"; // Import your background image
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
        <Header />
      </header>
      <main className={`relative min-h-screen bg-cover bg-center`} style={{ backgroundImage: `url(${backgroundImage.src})` }}>
        <div className="relative z-10">{children}</div>
        <div className="absolute inset-0 bg-black opacity-30 z-0"></div> {/* Optional: Add overlay */}
      </main>
    </div>
  );
}
